# environment config
gpu_id: 0
checkpoint_dir : experiments/yelp2018/BPR #模型保存的路径
#save_dataset: True
log_wandb: True
wandb_project: RecBole
wandb_name: BPR-yelp2018

# model config
embedding_size: 32

# dataset config
field_separator: "\t"  #指定数据集field的分隔符
seq_separator: " "   #指定数据集中token_seq或者float_seq域里的分隔符
USER_ID_FIELD: user_id #指定用户id域
ITEM_ID_FIELD: item_id #指定物品id域
RATING_FIELD: rating   #指定打分rating域
TIME_FIELD: timestamp  #指定时间域
NEG_PREFIX: neg_   #指定负采样前缀
#指定从什么文件里读什么列，这里就是从ml-1m.inter里面读取user_id, item_id, rating, timestamp这四列
load_col:
  inter: [user_id, item_id, rating, timestamp]

# training settings
epochs: 500  #训练的最大轮数
train_batch_size: 4096 #训练的batch_size
learner: adam #使用的pytorch内置优化器
learning_rate: 0.001 #学习率
eval_step: 1 #每次训练后做evalaution的次数
stopping_step: 10 #控制训练收敛的步骤数，在该步骤数内若选取的评测标准没有什么变化，就可以提前停止了
# evalution settings
eval_args: {group_by: user, order: TO, split: {'LS': 'valid_and_test'}, mode: uni100}  #对数据随机重排，设置按比例划分数据集
metrics: ["NDCG", "Recall", "MRR"] #评测标准
topk: [10, 20] #评测标准使用topk，设置成10评测标准就是["Recall@10", "MRR@10", "NDCG@10", "Hit@10", "Precision@10"]
valid_metric: NDCG@10 #选取哪个评测标准作为作为提前停止训练的标准
eval_batch_size: 4096 #评测的batch_size
